#!/usr/bin/env bash
set -e

# Open a shell-session in the specified container

container=$(docker ps --format "{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.CreatedAt}}" |
    fzf |
    choose 0)

cmd="docker exec -it $container sh"
echo "$cmd"
$cmd
