#!/usr/bin/env bash
set -e

args="$1"
format="table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.CreatedAt}}"

if [[ -n $args ]]; then
  docker ps "$args" --format "$format" | sed 1d
else
  docker ps --format "$format" | sed 1d
fi
