#!/usr/bin/env bash
set -eo pipefail

# Stops one or more running docker-containers

format="table {{.Names}}\t{{.Image}}\t{{.Status}}"
filter="status=running"

# find all running containers
containers=$(docker ps --format "$format" --filter "$filter" | sed 1d)

# select one or more running containers and join them to a single line
selected=$(echo "$containers" | fzf --multi | awk '{print $1}' | paste -sd " " -)

docker stop $(echo "$selected")
