#!/usr/bin/env bash
set -eo pipefail

# Starts one or more stopped docker-containers

format="table {{.Names}}\t{{.Image}}\t{{.Status}}"
filter="status=exited"

# find all stoppped containers
containers=$(docker ps --format "$format" --filter "$filter" | sed 1d)

# select one or more stoppped containers and join them to a single line
selected=$(echo "$containers" | fzf --multi | awk '{print $1}' | paste -sd " " -)

docker start $(echo "$selected")
