#!/usr/bin/env bash
set -e

# Bytter aktiv branch

git rev-parse --git-dir &> /dev/null || {
  echo "Not in git repo"
  exit
}

local_branches=$(git for-each-ref --format='%(refname:short)' refs/heads)
log_pattern="git log -b {} --pretty=format:'%h %d %s'"

chosen_branch=$(fzf --preview="$log_pattern" --exit-0 <<< "$local_branches")
git switch "$chosen_branch"
