#!/usr/bin/env bash
set -eo pipefail

help() {
  cat <<EOF
usage: $0 <command>

Commands:
    edit         Open selected file in \$EDITOR
    tig          View git-history of selected file in tig
    rm           Delete selected file
    cat          Echo contents of selected file
    copy-path    Copy path of selected file
    copy-content Copy contents of selected file

EOF
}

[[ $1 =~ ^(edit|tig|rm|cat|copy-path|copy-content)$ ]] || {
  help
  exit
}

choose_file() {
  fzf --preview='[[ $(file --mime {}) =~ binary ]] && echo "<binary>" ||
                (cat {}) 2> /dev/null | head -500' || exit
}

file=$(choose_file)

case "$1" in
edit) ${EDITOR:-vim} "$file" ;;
tig) tig "$file" ;;
rm) rm -i "$file" ;;
cat) cat "$file" ;;
copy-path) echo "$(pwd)/$file" | pbcopy ;;
copy-content) pbcopy <"$file" ;;
*) help ;;
esac
