#!/usr/bin/env bash
set -eo pipefail

# Select a remote branch with fzf then check it out locally

remote_branches=$(git-remote-heads | rg -v "(master|main|develop|HEAD)")

[[ -z $remote_branches ]] && {
  echo "No remote, non-standard branches" >&2
  exit 1
}

remote_branch=$(fzf <<< "$remote_branches")
git switch "$remote_branch"
