#!/usr/bin/env bash
set -e

# Lar bruker velge en gpg-nøkkel ved navn/epost og eksporterer nøkkel til .gpg

key=$(gpg-select-key)

# filnavn: alt i epost frem til alfakrøll, punktum erstattet med bindestrek
filename="$(echo $key | cut -d @ -f 1 | sed 's/\./-/g').gpg"

# eksporter nøkkel
gpg --armor --output "$filename" --export "$key"
