#!/usr/bin/env bash
set -e

# Lar bruker velge en gitt GPG-nøkkel

# get all keys
keys=$(gpg --list-keys)

# extract lines containing name + email
users=$(echo "$keys" | rg uid | awk -F "] " '{print $2}' | sort)

# prompt user to select a key
key=$(echo "$users "| fzf --exit-0)

# extract email from chosen key
echo "$key "| cut -d "<" -f 2 | cut -d ">" -f 1

