#!/usr/bin/env bash
set -e

# Installerer en gitt versjon av kubectl

[[ -z $1 ]] && {
  echo "Usage: $0 [version]"
  exit 1
}

BIN="$HOME/.local/bin/kubectl"

kubectl_version() {
  command -v "$BIN" >/dev/null && {
    $BIN version --short | rg client | choose 2 | sd '^v' ''
  }
}

oldVersion=$(kubectl_version)
[[ $oldVersion = "$1" ]] && {
  echo "Version v$1 is already installed, exiting"
  exit 1
}
echo "Installing kubectl v$1 (current version: v$oldVersion)"

cd "$(mktemp -d)"

echo "> Downloading kubectl v$1 .."
curl -LOs https://storage.googleapis.com/kubernetes-release/release/v"${1}"/bin/darwin/amd64/kubectl

echo "> Making kubectl executable .."
chmod +x ./kubectl

echo "> Moving kubectl to /usr/local/bin .."
mv ./kubectl "$BIN"

echo "Successfully installed version $(kubectl_version)"
