#!/usr/bin/env bash
set -eo pipefail

# kills a process using fuzzy-match

pid=$(ps axo user=,pid=,time=,args= | sed 1d | fzf | choose 1)
echo "killing process:"
ps "$pid" -o pid=,user=,command=
[[ -n $pid ]] && kill -9 "$pid"
