#!/usr/bin/env bash
[[ -z $1 ]] && exit

[[ -f $1 ]] && {
  echo "$1 already exists"
  exit
}

cat << EOF > "$1"
#!/usr/bin/env bash

EOF
chmod +x "$1"
tmux splitw -d "ls $1 | entr -c ./$1"
$EDITOR "$1" -c 'set ft=sh'
