#!/usr/bin/env bash
set -eo pipefail

# find all stoppped containers
container=$(docker ps --all --format "{{.Names}}\t{{.Image}}\t{{.Status}}" |
    rg -vw "Up" |
    fzf --multi |
    choose 0 |
    paste -sd " " -)

docker start $(echo "$container")
