#!/usr/bin/env bash
set -eo pipefail

# stops one or more running docker-containers

container=$(docker ps --format "{{.Names}}\t{{.Image}}\t{{.Status}}" |
    fzf --multi |
    choose 0 |
    paste -sd " " -)

echo "stopping: $container"
docker stop "$container"
