#!/usr/bin/env bash
set -eo pipefail

# switch active branch

git rev-parse --git-dir &>/dev/null || {
  echo "not in git repo, exiting." >&2
  exit 1
}

git for-each-ref --format='%(refname:short)' refs/heads |
  fzf --preview="git log -b {} --pretty=format:'%h %d %s'" |
  xargs git switch
