#!/usr/bin/env bash
set -eo pipefail

# switch active branch
refs=$(git for-each-ref --format='%(refname:short)' refs/heads)
echo "$refs" |
  fzf --preview="git log -b {} --pretty=format:'%h %d %s'" |
  xargs git switch
