#!/usr/bin/env bash
set -eo pipefail

# create a .tool-versions in curdir for the desired plugin/version

command -v asdf &>/dev/null || {
  echo "asdf not installed, exiting" >&2
  exit 1
}

plugin=$(asdf plugin list | fzf)
echo "plugin: $plugin"
versions=$(asdf list "$plugin" 2>&1) # asdf doesn't return 1 but writes to stderr
[[ "$versions" == *"No versions installed"* ]] && {
  echo "error: $(xargs <<< $versions)" # xargs for ltrim
  exit 1
}
choice=$(cat "$versions"| sd '[* ]' '' | fzf)

asdf local "$plugin" "$version"
